# Generated by Django 4.2.5 on 2023-09-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_patient_info_medical_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_info',
            name='about',
            field=models.TextField(),
        ),
    ]
